services:
  Sales.Subscriptions.application.SubscriptionCreateService:
    class: ../../../../src/Contexts/Sales/Subscriptions/application/SubscriptionCreateService
    arguments: ["@Sales.Subscriptions.repositories.SubscriptionRepository"]
